---
openapi: 3.0.0
info:
  title: DeliverySwab's third party APIs
  description: "APIs for requesting and managing **deliveries**,**swab** orders and **payments**. Details on the interfaces of the services offered by DeliverySwab partners are provided below. In particular: **delivery third party, supplier third party, payments third party**."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:9090/
    description: Local Server
tags:
  - name: analyzely
    description: APIs of the DeliverySwab's analize third party for requesting and managing **deliveries**
  - name: supplierly
    description: APIs of the DeliverySwab's supplier third party for requesting and managing **raw material orders**
  - name: bankly
    description: APIs of the DeliverySwab's payment third party for requesting and managing **payments**
paths:
  /analyzely/analyze:
    post:
      tags:
        - analyzely
      summary: Make a request to Analizely
      description: This API allows to submit a request for a new delivery
      operationId: handleAnalysis
      requestBody:
        description: Details of the customer that made the swab test
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnalysisRequest"
        required: true
      responses:
        "200":
          description: The shipment has been taken over
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analysis"
        "400":
          description: Bad request, the address is invalid or not served by Deliverly
      x-swagger-router-controller: Analyzely
  /analyzely/analyze/{ssn}:
    get:
      tags:
        - analyzely
      summary: Get details of an existing swab analysis request
      description: This API allows to get details about a analysis request
      operationId: getAnalysisDetails
      parameters:
        - name: ssn
          in: path
          description: Analysis identifier
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Analysis details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analysis"
        "404":
          description: Delivery not found
      x-swagger-router-controller: Analyzely
  /supplierly/swabs:
    get:
      tags:
        - supplierly
      summary: Get the available swabs
      description: This API allows to get the available swabs
      operationId: getSwabs
      responses:
        "200":
          description: Swabs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Swabs"
      x-swagger-router-controller: Supplierly
  /supplierly/order:
    post:
      tags:
        - supplierly
      summary: Place a swab stock order to Supplierly
      description: This API allows to submit a swab stock order
      operationId: orderSwabs
      requestBody:
        description: Details of the order to be placed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
        required: true
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Bad request, required materials do not exist or invalid order
      x-swagger-router-controller: Supplierly
  /bankly/payment:
    post:
      tags:
        - bankly
      summary: Emit a payment
      description: This API allows to emit a payment
      operationId: emitPayment
      requestBody:
        description: Details of the payment to be placed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
        required: true
      responses:
        "200":
          description: Payment successfully processed
        "400":
          description: Insufficient credit to execute the transaction
        "404":
          description: Invalid IBAN
      x-swagger-router-controller: Bankly
components:
  schemas:
    AnalysisRequest:
      properties:
        name:
          type: string
        surname:
          type: string
        mail:
          type: string
        ssn:
          type: string
        date:
          type: string
      example:
        name: Mario
        surname: Rossi
        mail: mario.rossi100@gmail.it
        ssn: MRARSS97H28C933E
        date: 28/6/2022
    Analysis:
      properties:
        status:
          type: string
          enum:
            - processing
            - terminated
        swabresult:
          type: string
          enum:
            - not analyzed
            - positive
            - negative
        name:
          type: string
        surname:
          type: string
        mail:
          type: string
        ssn:
          type: string
        date:
          type: string
      example:
        name: Mario
        surname: Rossi
        mail: mario.rossi100@gmail.com
        ssn: MRARSS97H28C933E
        date: 28/6/2022
        status: terminated
        swabresult: negative
    OrderRequest:
      type: object
      properties:
        id:
          type: integer
        quantity:
          type: integer
      example:
        id: 0
        quantity: 4
    Order:
      properties:
        deliveryDate:
          type: string
        cost:
          type: number
        iban:
          type: string
        swabs:
          $ref: "#/components/schemas/OrderRequest"
      example:
        deliveryDate: 01/09/2022
        cost: 1050.5
        iban: IT78-F569-3411-1000-0000-0145-123
        swabs:
          id: 0
          quantity: 4
    PaymentRequest:
      properties:
        iban:
          type: string
        amount:
          type: number
      example:
        iban: IT78-F569-3411-1000-0000-0145-123
        amount: 1000
    Swabs:
      type: object
      properties:
        id:
          type: integer
          format: int64
        price:
          type: number
        availability:
          type: integer
      example:
        id: 0
        price: 10
        availability: 7
